name: Bin

on: [push]

jobs:
  ppx:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    name: Bin
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: packages/reason-relay-bin
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.19.0
        env:
          CI: true
      - name: Install esy
        run: npm install -g esy
      - name: Build ReasonRelayBin
        uses: esy/github-action@v1
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}
          working-directory: packages/reason-relay-bin
      - name: Test ReasonRelayBin
        run: esy test -vvv
      - name: Upload ReasonRelayBin artifact
        uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.platform }}
          path: packages/reason-relay-bin/_esy/default/build/default/bin/ReasonRelayBin.exe
          if-no-files-found: error
